module.exports = [
    {
        association: "1D",
        number: "2",
        suit: "Diamond",
        face: false,
    },
    {
        association: "2D",
        number: "3",
        suit: "Diamond",
        face: false,
    },
    {
        association: "3D",
        number: "4",
        suit: "Diamond",
        face: false,
    },
    {
        association: "4D",
        number: "5",
        suit: "Diamond",
        face: false,
    },
    {
        association: "5D",
        number: "6",
        suit: "Diamond",
        face: false,
    },
    {
        association: "6D",
        number: "7",
        suit: "Diamond",
        face: false,
    },
    {
        association: "7D",
        number: "8",
        suit: "Diamond",
        face: false,
    },
    {
        association: "8D",
        number: "9",
        suit: "Diamond",
        face: false,
    },
    {
        association: "9D",
        number: "10",
        suit: "Diamond",
        face: false,
    },
    {
        association: "10D",
        number: "J",
        suit: "Diamond",
        face: true,
    },
    {
        association: "11D",
        number: "Q",
        suit: "Diamond",
        face: true,
    },
    {
        association: "12D",
        number: "K",
        suit: "Diamond",
        face: true,
    },
    {
        association: "13D",
        number: "A",
        suit: "Diamond",
        face: true,
    },
    {
        association: "1S",
        number: "2",
        suit: "Spade",
        face: false,
    },
    {
        association: "2S",
        number: "3",
        suit: "Spade",
        face: false,
    },
    {
        association: "3S",
        number: "4",
        suit: "Spade",
        face: false,
    },
    {
        association: "4S",
        number: "5",
        suit: "Spade",
        face: false,
    },
    {
        association: "5S",
        number: "6",
        suit: "Spade",
        face: false,
    },
    {
        association: "6S",
        number: "7",
        suit: "Spade",
        face: false,
    },
    {
        association: "7S",
        number: "8",
        suit: "Spade",
        face: false,
    },
    {
        association: "8S",
        number: "9",
        suit: "Spade",
        face: false,
    },
    {
        association: "9S",
        number: "10",
        suit: "Spade",
        face: false,
    },
    {
        association: "10S",
        number: "J",
        suit: "Spade",
        face: true,
    },
    {
        association: "11S",
        number: "Q",
        suit: "Spade",
        face: true,
    },
    {
        association: "12S",
        number: "K",
        suit: "Spade",
        face: true,
    },
    {
        association: "13S",
        number: "A",
        suit: "Spade",
        face: true,
    },
    {
        association: "1C",
        number: "2",
        suit: "Club",
        face: false,
    },
    {
        association: "2C",
        number: "3",
        suit: "Club",
        face: false,
    },
    {
        association: "3C",
        number: "4",
        suit: "Club",
        face: false,
    },
    {
        association: "4C",
        number: "5",
        suit: "Club",
        face: false,
    },
    {
        association: "5C",
        number: "6",
        suit: "Club",
        face: false,
    },
    {
        association: "6C",
        number: "7",
        suit: "Club",
        face: false,
    },
    {
        association: "7C",
        number: "8",
        suit: "Club",
        face: false,
    },
    {
        association: "8C",
        number: "9",
        suit: "Club",
        face: false,
    },
    {
        association: "9C",
        number: "10",
        suit: "Club",
        face: false,
    },
    {
        association: "10C",
        number: "J",
        suit: "Club",
        face: true,
    },
    {
        association: "11C",
        number: "Q",
        suit: "Club",
        face: true,
    },
    {
        association: "12C",
        number: "K",
        suit: "Club",
        face: true,
    },
    {
        association: "13C",
        number: "A",
        suit: "Club",
        face: true,
    },
    {
        association: "1H",
        number: "2",
        suit: "Heart",
        face: false,
    },
    {
        association: "2H",
        number: "3",
        suit: "Heart",
        face: false,
    },
    {
        association: "3H",
        number: "4",
        suit: "Heart",
        face: false,
    },
    {
        association: "4H",
        number: "5",
        suit: "Heart",
        face: false,
    },
    {
        association: "5H",
        number: "6",
        suit: "Heart",
        face: false,
    },
    {
        association: "6H",
        number: "7",
        suit: "Heart",
        face: false,
    },
    {
        association: "7H",
        number: "8",
        suit: "Heart",
        face: false,
    },
    {
        association: "8H",
        number: "9",
        suit: "Heart",
        face: false,
    },
    {
        association: "9H",
        number: "10",
        suit: "Heart",
        face: false,
    },
    {
        association: "10H",
        number: "J",
        suit: "Heart",
        face: true,
    },
    {
        association: "11H",
        number: "Q",
        suit: "Heart",
        face: true,
    },
    {
        association: "12H",
        number: "K",
        suit: "Heart",
        face: true,
    },
    {
        association: "13H",
        number: "A",
        suit: "Heart",
        face: true,
    },
]